
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:4 (find_package)"
    message: |
      The target system is: Generic - 4.1.99 - arm
      The host system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:4 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/aguat/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      c:/users/aguat/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:/users/aguat/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib\\libc.a(lib_a-exit.o): in function `exit':
      exit.c:(.text.exit+0x34): undefined reference to `_exit'
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:4 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Users/aguat/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is GNU, found in:
        D:/aguat/Documents/zephyr/zephyr_main/build_fdrmmcxc444_threads/CMakeFiles/4.0.3/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:4 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: C:/Users/aguat/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      c:/users/aguat/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:/users/aguat/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib\\libc.a(lib_a-exit.o): in function `exit':
      exit.c:(.text.exit+0x34): undefined reference to `_exit'
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:4 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Users/aguat/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is GNU, found in:
        D:/aguat/Documents/zephyr/zephyr_main/build_fdrmmcxc444_threads/CMakeFiles/4.0.3/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1271 (message)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CMakeDetermineASMCompiler.cmake:139 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules/kernel.cmake:135 (enable_language)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:4 (find_package)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      arm-zephyr-eabi-gcc.exe (Zephyr SDK 0.17.0) 12.2.0
      Copyright (C) 2022 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CheckSourceCompiles.cmake:104 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "C:/Program Files/CMake/share/cmake-4.0/Modules/CheckCCompilerFlag.cmake:56 (cmake_check_compiler_flag)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules/extensions.cmake:2332 (check_c_compiler_flag)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules/extensions.cmake:1191 (check_compiler_flag)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules/extensions.cmake:2371 (zephyr_check_compiler_flag)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules/extensions.cmake:2347 (target_cc_option_fallback)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules/extensions.cmake:155 (target_cc_option)"
      - "D:/aguat/Documents/zephyr/zephyr_main/zephyr/CMakeLists.txt:567 (zephyr_cc_option)"
    directories:
      source: "D:/aguat/Documents/zephyr/zephyr_main/build_fdrmmcxc444_threads/CMakeFiles/CMakeScratch/TryCompile-pwvab6"
      binary: "D:/aguat/Documents/zephyr/zephyr_main/build_fdrmmcxc444_threads/CMakeFiles/CMakeScratch/TryCompile-pwvab6"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "D:/aguat/Documents/zephyr/zephyr_main/zephyr/cmake/modules"
    buildResult:
      variable: "check_fmacro_prefix_map_D__aguat_Documents_GitHub_Zephyr_SEA2_fdrmmcxc444_threads_CMAKE_SOURCE_DIR_C__nostartfiles__nostdlib__isystem__c__users_aguat_zephyr_sdk_0_17_0_arm_zephyr_eabi_bin____lib_gcc_arm_zephyr_eabi_12_2_0_include___isystem__c__users_aguat_zephyr_sdk_0_17_0_arm_zephyr_eabi_bin____lib_gcc_arm_zephyr_eabi_12_2_0_include_fixed___Wl___unresolved_symbols_ignore_in_object_files__Wl___entry_0__fuse_ld_bfd"
      cached: true
      stdout: |
        Change Dir: 'D:/aguat/Documents/zephyr/zephyr_main/build_fdrmmcxc444_threads/CMakeFiles/CMakeScratch/TryCompile-pwvab6'
        
        Run Build Command(s): C:/ProgramData/chocolatey/bin/ninja.exe -v cmTC_26992
        [1/2] C:\\Users\\aguat\\zephyr-sdk-0.17.0\\arm-zephyr-eabi\\bin\\arm-zephyr-eabi-gcc.exe -Dcheck_fmacro_prefix_map_D__aguat_Documents_GitHub_Zephyr_SEA2_fdrmmcxc444_threads_CMAKE_SOURCE_DIR_C__nostartfiles__nostdlib__isystem__c__users_aguat_zephyr_sdk_0_17_0_arm_zephyr_eabi_bin____lib_gcc_arm_zephyr_eabi_12_2_0_include___isystem__c__users_aguat_zephyr_sdk_0_17_0_arm_zephyr_eabi_bin____lib_gcc_arm_zephyr_eabi_12_2_0_include_fixed___Wl___unresolved_symbols_ignore_in_object_files__Wl___entry_0__fuse_ld_bfd  -nostartfiles -nostdlib -isystem "c:/users/aguat/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/include" -isystem "c:/users/aguat/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/include-fixed" -Wl,--unresolved-symbols=ignore-in-object-files -Wl,--entry=0 -fuse-ld=bfd   -fmacro-prefix-map=D:/aguat/Documents/GitHub/Zephyr-SEA2/fdrmmcxc444_threads=CMAKE_SOURCE_DIR -o CMakeFiles/cmTC_26992.dir/src.c.obj -c D:/aguat/Documents/zephyr/zephyr_main/build_fdrmmcxc444_threads/CMakeFiles/CMakeScratch/TryCompile-pwvab6/src.c
        [2/2] C:\\Windows\\system32\\cmd.exe /C "cd . && C:\\Users\\aguat\\zephyr-sdk-0.17.0\\arm-zephyr-eabi\\bin\\arm-zephyr-eabi-gcc.exe -nostartfiles -nostdlib -isystem "c:/users/aguat/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/include" -isystem "c:/users/aguat/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/include-fixed" -Wl,--unresolved-symbols=ignore-in-object-files -Wl,--entry=0 -fuse-ld=bfd  CMakeFiles/cmTC_26992.dir/src.c.obj -o cmTC_26992   && cd ."
        
      exitCode: 0
...
